repos:
- repo: git://github.com/nbQA-dev/nbQA
  rev: "7ab6f126a39765a9a2887dbff4e943a57115a6e6"
  hooks:
  - id: nbqa-mypy
  - id: nbqa-black
  - id: nbqa-isort

- repo: git://github.com/guykisel/prospector-mirror
  rev: "7ff847e779347033ebbd9e3b88279e7f3a998b45"
  hooks:
  - id: prospector