repos:
- repo: git://github.com/nbQA-dev/nbQA
  rev: "7ab6f126a39765a9a2887dbff4e943a57115a6e6"
  hooks:
  - id: nbqa-mypy
  - id: nbqa-black
  - id: nbqa-isort

- repo: local
  hooks:
  - id: prospector
    name: prospector
    stages: [commit]
    language: system
    entry: poetry run prospector --profile-path prospector.yaml
    types: [python]
    require_serial: true